apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: devops-alerts
  namespace: monitoring
  labels:
    app.kubernetes.io/name: mimir-rules
    team: devops
spec:
  groups:
    - name: services
      interval: 1m
      rules:
        - alert: GreaterThan2
          expr: mimirtool_test_metric > 2
          for: 1m
          labels:
            team: devops
          annotations:
            summary: "mimirtool_test_metric is above 2"
        - alert: GreaterThan3
          expr: mimirtool_test_metric > 3
          for: 1m
          labels:
            team: devops
          annotations:
            summary: "mimirtool_test_metric is above 3"
