apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: platform-alerts
  namespace: monitoring
  labels:
    team: platform
spec:
  route:
    groupBy: ["alertname", "team"]
    groupWait: "30s"
    groupInterval: "5m"
    repeatInterval: "4h"
    receiver: platform
    matchers:
      - name: team
        value: platform
  receivers:
    - name: platform
      webhookConfigs:
        - url: "https://oncall-prod-us-central-0.grafana.net/oncall/integrations/v1/alertmanager/7DgwRUZa8N25KXMFdqKnoTCNd/"
